name: testing
version: "1.0"
server:
    type: purpur
    minecraft_version: 1.20.4
    build: latest
plugins:
    - name: Fabric API
      version: 0.97.3+1.20.4
      modrinth_id: fabric-api
    - name: Sodium
      version: mc1.20.4-0.5.8
      modrinth_id: sodium
    - name: VaultUnlocked
      version: 2.17.0
      modrinth_id: vaultunlocked
    - name: EssentialsX
      version: 2.21.2
      modrinth_id: essentialsx
    - name: BattleTracker
      version: 4.0.2-SNAPSHOT-19
      modrinth_id: battletracker
    - name: pvp-toggle
      version: 3.1.3
      modrinth_id: pvp-toggle
    - name: Chunky
      version: 1.4.40
      modrinth_id: chunky
    - name: WorldEdit
      version: 7.3.10-beta-01
      modrinth_id: worldedit
    - name: Emotecraft
      version: 2.4.0-a.f140890e
      modrinth_id: emotecraft
    - name: CalcMod
      version: fabric-1.20.2-1.3.1
      modrinth_id: calcmod
    - name: ViaVersion
      version: 5.5.2-SNAPSHOT+861
      modrinth_id: viaversion
    - name: Tab
      version: "0.1"
      modrinth_id: easytab
    - name: Geyser
      version: 2.9.1-b997
      modrinth_id: geyser
    - name: Terra
      version: 6.4.3-BETA-bukkit
      modrinth_id: terra
    - name: SkinsRestorer
      version: 15.9.0
      modrinth_id: skinsrestorer
    - name: Dynmap®
      version: 3.7-beta-8
      modrinth_id: dynmap
    - name: RankedPlay
      version: 1.1.4
      modrinth_id: rankedplay
